Feature #180537199 – Import proteomics differential experiments
ebi-gene-expression-group/atlas-web-bulk pull request #106
Opened 2022-01-18 17:50 UTC by alfonsomunozpomer

Add validation of proteomics differential experiments to be like differential RNA-Seq, but without raw counts files. It includes some `atlas-web-core` changes (see below).

This PR is accompanied by https://github.com/ebi-gene-expression-group/atlas-web-core/pull/86.

2022-01-19 09:34 UTC, upendrakumbham commented on app/src/test/java/uk/ac/ebi/atlas/experimentimport/ExperimentCheckerIT.java
> +                PROTEOMICS_BASELINE_DIA,
Thanks for Adding 'DIA' experiment type here

2022-01-19 12:00 UTC, upendrakumbham commented on app/src/test/java/uk/ac/ebi/atlas/experimentimport/ExperimentCheckerIT.java
> +                PROTEOMICS_BASELINE_DIA,
I ran this class, one of the test cases is failing.
Here is the details: 
```
ExperimentCheckerIT > checkAllFiles(String, ExperimentType) > uk.ac.ebi.atlas.experimentimport.ExperimentCheckerIT.checkAllFiles(String, ExperimentType)[2] FAILED
    java.lang.IllegalStateException at ExperimentCheckerIT.java:64
```
Can you please run this class on your side?

2022-01-19 12:01 UTC, upendrakumbham commented on app/src/test/java/uk/ac/ebi/atlas/experimentimport/ExpressionAtlasExperimentCheckerTest.java
> +                        "<assay>A</assay>" +
All tests passed.

2022-01-19 12:07 UTC, upendrakumbham requested changes
The code looks good to me and has lots of cleanup.

I ran this class, one of the test cases is failing.  
```
Here is the details:
ExperimentCheckerIT > checkAllFiles(String, ExperimentType) > uk.ac.ebi.atlas.experimentimport.ExperimentCheckerIT.checkAllFiles(String, ExperimentType)[2] FAILED
    java.lang.IllegalStateException at ExperimentCheckerIT.java:64

```
Can you please run this class on your side?

I'm not sure why cli and war checks are failing in the PR, can you please check.

2022-01-19 12:56 UTC, upendrakumbham commented on app/src/test/java/uk/ac/ebi/atlas/experimentimport/ExperimentCheckerIT.java
> +                PROTEOMICS_BASELINE_DIA,
I think we should think about renaming this `ExperimentCheckerIT.java` to `ExpressionAtlasExperimentCheckerIT.java` as ExperimentChecker is an interface.

2022-01-19 12:57 UTC, alfonsomunozpomer commented
I run all the tests and they passed:
```bash
ExperimentCheckerIT > checkAllFiles(String, ExperimentType) > uk.ac.ebi.atlas.experimentimport.ExperimentCheckerIT.checkAllFiles(String, ExperimentType)[1] PASSED

ExperimentCheckerIT > checkAllFiles(String, ExperimentType) > uk.ac.ebi.atlas.experimentimport.ExperimentCheckerIT.checkAllFiles(String, ExperimentType)[2] PASSED

ExperimentCheckerIT > checkAllFiles(String, ExperimentType) > uk.ac.ebi.atlas.experimentimport.ExperimentCheckerIT.checkAllFiles(String, ExperimentType)[3] PASSED

ExperimentCheckerIT > checkAllFiles(String, ExperimentType) > uk.ac.ebi.atlas.experimentimport.ExperimentCheckerIT.checkAllFiles(String, ExperimentType)[4] PASSED

ExperimentCheckerIT > checkAllFiles(String, ExperimentType) > uk.ac.ebi.atlas.experimentimport.ExperimentCheckerIT.checkAllFiles(String, ExperimentType)[5] PASSED

ExperimentCheckerIT > checkAllFiles(String, ExperimentType) > uk.ac.ebi.atlas.experimentimport.ExperimentCheckerIT.checkAllFiles(String, ExperimentType)[6] PASSED

ExperimentCheckerIT > checkAllFiles(String, ExperimentType) > uk.ac.ebi.atlas.experimentimport.ExperimentCheckerIT.checkAllFiles(String, ExperimentType)[7] PASSED

ExperimentCheckerIT > checkAllFiles(String, ExperimentType) > uk.ac.ebi.atlas.experimentimport.ExperimentCheckerIT.checkAllFiles(String, ExperimentType)[8] PASSED

BUILD SUCCESSFUL in 10s
7 actionable tasks: 1 executed, 6 up-to-date
```

Maybe you need to add E-PROT-39 to your integration environment (Postgres and Solr)?

2022-01-19 12:59 UTC, alfonsomunozpomer commented
Probably the build fails because I was too hasty and deleted the remote branch, let me restore it and I’ll try again.

2022-01-19 14:22 UTC, upendrakumbham commented
> Probably the build fails because I was too hasty and deleted the remote branch in `atlas-web-core`, let me restore it and I’ll try again.

Yeah, @alfonsomunozpomer. I don't have E-PROT-39 in the Solr.

2022-01-19 14:27 UTC, upendrakumbham approved these changes
All LGTM! Please merge away.

2022-01-19 14:27 UTC, merged

2022-01-20 10:26 UTC, pcm32 commented
This PR broke the Github actions on 14e4d53 I suspect...

2022-01-20 10:28 UTC, pcm32 commented
Here is the message https://github.com/ebi-gene-expression-group/atlas-web-bulk/actions/runs/1718175139 (same for both I think).