Experiment Design service
ebi-gene-expression-group/atlas-web-bulk pull request #151
Opened 2023-03-28 13:47 UTC by haideriqbal

This PR implements controller for getting experiment design data in bulk expression atlas. This is extension to the single cell [PR](https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/324) and web-core [PR](https://github.com/ebi-gene-expression-group/atlas-web-core/pull/123).

NOTE: PLEASE SEE THE TESTING INFRASTRUCTURE HAS BEEN CHANGED IN THIS PR. BULK WAS USING OLD WAY OF TESTING USING `H2` DATABASE WHICH HAS BEEN REPLACED NOW WITH CONTAINERISED TESTING.

2023-09-28 09:42 UTC, upendrakumbham commented on app/src/main/java/uk/ac/ebi/atlas/experiments/ExperimentDesignController.java
> +            throw new IllegalArgumentException("Page number must be greater than 0");
We can optimise two if conditions into one if with OR logical stmt.

```
if (pageNo < 1 || pageSize<1) {
     throw new IllegalArgumentException("Page number/page size must be greater than 0"
}
```

2023-10-03 13:14 UTC, ke4 requested changes
I added some change requests that we should do.
I am going to apply them today.

2023-10-03 13:14 UTC, ke4 commented on app/src/main/java/uk/ac/ebi/atlas/experimentpage/content/ExperimentPageContentService.java
> +/*        if (dataFileHub.getExperimentFiles(experiment.getAccession()).experimentDesign.exists()) {
Why is this commented out? If we don't need this code fragment, then please delete it.

2023-10-03 13:14 UTC, ke4 commented on docker/prepare-dev-environment/postgres/docker-entrypoint.sh
> +cd /root/db-scxa/bin
We don't need this file anymore as we are using docker-compose.yml instead of this one. Please, remove these changes. Thanks

2023-10-03 13:14 UTC, ke4 commented on docker/prepare-dev-environment/postgres/Dockerfile
We also don't need all of these changes, Solr8 compatible version has been already merged into develop. Could you please remove these changes? Thanks

2023-10-03 13:14 UTC, ke4 commented on app/src/test/java/uk/ac/ebi/atlas/configuration/TestConfig.java
> +@ComponentScan(basePackages = "uk.ac.ebi.atlas")
Why were the `include` and `exclude` filters removed? If it is OK to remove them, then please also change the comment above.

2023-10-03 13:14 UTC, ke4 commented on app/src/test/java/uk/ac/ebi/atlas/experiments/ExperimentDesignControllerWIT.java
> +    void hasExperimentDesignDataWithoutAnyParameter() throws Exception {
```suggestion
void whenExperimentDesignHasNoParameterThenReturnsOK() throws Exception {
```

2023-10-03 13:14 UTC, ke4 commented on app/src/test/java/uk/ac/ebi/atlas/experiments/ExperimentDesignControllerWIT.java
> +    void hasValidExperimentDesignDataWithPageSizeParameter() throws Exception {
```suggestion
void whenExperimentDesignHasPageSizeParameterThenReturnsOK() throws Exception {
```

2023-10-03 13:14 UTC, ke4 commented on app/src/test/java/uk/ac/ebi/atlas/experiments/ExperimentDesignControllerWIT.java
> +    void throwsErrorWithInValidPageSizeParameter() throws Exception {
```suggestion
void whenExperimentDesignHasInvalidPageSizeParameterThenThrowsError() throws Exception {
```

2023-10-03 13:14 UTC, ke4 commented on app/src/test/java/uk/ac/ebi/atlas/experiments/ExperimentDesignControllerWIT.java
> +    void throwsErrorWithInValidPageNoParameter() throws Exception {
```suggestion
void whenExperimentDesignHasInvalidPageNoParameterThenThrowsError() throws Exception {
```

2023-10-03 13:14 UTC, ke4 commented on app/src/test/java/uk/ac/ebi/atlas/experiments/ExperimentDesignControllerWIT.java
> +                        .param("pageSize", "10"))
We should create a constant from the magic number.

2023-10-03 13:14 UTC, ke4 commented on app/src/test/java/uk/ac/ebi/atlas/experiments/ExperimentDesignControllerWIT.java
> +                        .param("pageSize", "0"))
We should create a constant from the magic number.

2023-10-03 13:14 UTC, ke4 commented on app/src/test/java/uk/ac/ebi/atlas/experiments/ExperimentDesignControllerWIT.java
> +                        .param("pageNo", "0"))
We should create a constant from the magic number.

2023-10-03 16:47 UTC, upendrakumbham approved these changes
LGTM!

2023-10-04 08:05 UTC, ke4 approved these changes
👍

2023-10-04 09:07 UTC, merged