Correct the mapping on external resources links in supplementary information page
ebi-gene-expression-group/atlas-web-bulk pull request #204
Opened 2024-06-21 09:28 UTC by lingyun1010

This is a big change on external resources links, basically we would like to decouple the logic from experiment type and the external resources. The detailed rules are given by Silvie stated in the related issue.

https://github.com/ebi-gene-expression-group/atlas-web-bulk/issues/195

2024-07-03 15:33 UTC, ke4 requested changes
Just a tiny one. Thanks for your work

2024-07-03 15:33 UTC, ke4 commented on app/src/main/java/uk/ac/ebi/atlas/experimentpage/ExpressionAtlasContentService.java
>          ImmutableList.Builder<ExternallyAvailableContent> arrayExpressAndOtherExternalResourcesLinks = ImmutableList.builder();
We can just name this as `externalResourcesLinks`.

```suggestion
        var externalResourcesLinks = ImmutableList.builder();
```

2024-07-10 09:38 UTC, ke4 requested changes
As I mentioned already in your other related PRs: you need to fix `atlas-web-core` submodule to base on the latest changes.
Thanks

2024-07-15 15:19 UTC, ke4 commented
This PR also contains some of the commits twice.
Could you clear this, please?
Thanks

2024-07-15 15:19 UTC, ke4 reviewed
This PR also contains some of the commits twice.
Could you clear this, please?
Thanks

2024-07-16 15:42 UTC, lingyun1010 commented
> This PR also contains some of the commits twice. Could you clear this, please? Thanks

My git is doing something duplicate ones automatically when I rebase on the atlas-develop-core `develop` branch, otherwise, even though I updated the atlas-web-core, the github checks still got a conflict issue ( like I mentioned here: https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/427#issuecomment-2220560900). So I think, I created a new rebased branch on the latest atlas-web-core submodule branch, without my previous commits and then merged into this one.

2024-07-19 15:04 UTC, ke4 approved these changes, later dismissed
LGTM

2024-07-19 15:07 UTC, ke4 submitted a review, later dismissed
LGTM 2nd try

2024-07-23 08:51 UTC, ke4 approved these changes, later dismissed
3rd try: LGTM!

2024-07-23 10:59 UTC, merged