Add container testing
ebi-gene-expression-group/atlas-web-bulk pull request #84
Opened 2021-08-26 16:54 UTC by haideriqbal

You will need the latest data and pg-dump to make sure all tests are passing. Also, you need to create suggesters for some tests. Otherwise, follow the SOP and it will work smoothly.

2021-09-01 16:34 UTC, alfonsomunozpomer requested changes
A few minor edits to address. Other than that all good.

2021-09-01 16:34 UTC, alfonsomunozpomer commented on README.md
> +ATLAS_DATA_PATH=/path/to/your/scxa/data \
A wild `scxa` escaped here...

2021-09-01 16:34 UTC, alfonsomunozpomer commented on README.md
> +```
I strongly advise against this. You might have other stopped containers unrelated to the project (I usually do) that I don’t want to remove.

2021-09-01 16:34 UTC, alfonsomunozpomer commented on README.md
> +ATLAS_DATA_PATH=/path/to/your/scxa/data \
Another wild `scxa` here!

2021-09-01 16:34 UTC, alfonsomunozpomer commented on README.md
> +scxa-gradle bash -c '
And here...

2021-09-01 16:34 UTC, alfonsomunozpomer commented on README.md
> +ATLAS_DATA_PATH=/path/to/your/scxa/data \
:eyes:

2021-09-01 16:34 UTC, alfonsomunozpomer commented on README.md
> +scxa-gradle bash -c '
:eyes:

2021-09-01 16:34 UTC, alfonsomunozpomer commented on app/src/main/java/uk/ac/ebi/atlas/download/DownloadController.java
> +            ftpClient.enterLocalPassiveMode();
Interesting...

2021-09-01 16:34 UTC, alfonsomunozpomer commented on app/src/test/java/uk/ac/ebi/atlas/download/DownloadControllerWIT.java
> +class DownloadControllerWIT {
:+1:

2021-09-01 16:34 UTC, alfonsomunozpomer commented on docker/docker-compose-postgres-test.yml
> +    command: -c max_wal_size=2GB
Do we need this? For fixtures  WAL shouldn’t be an issue since they are small transactions.

2021-09-17 07:22 UTC, lingyun1010 reviewed
I cannot comment on the lines those not your commits, but please look into README file, like line 43, there are some staled instructions from scxa.

2021-09-21 09:23 UTC, upendrakumbham approved these changes
Remove this line 'git clone --recurse-submodules https://github.com/ebi-gene-expression-group/atlas-web-core.git && \' from the Readme as core project became submodule now. All looks good to me.

2021-09-21 13:56 UTC, alfonsomunozpomer approved these changes
I couldn’t spot any further issues. To me everything looks good and ready to merge.

2021-09-22 07:50 UTC, lingyun1010 commented on README.md
> +In the `atlas-web-bulk-cell/docker` directory run the following:
The following bash code is not working for the new docker compose version anymore, please modify it to the latest command.

2021-09-22 14:13 UTC, lingyun1010 approved these changes
All good for me!

2021-09-24 13:41 UTC, merged