Feature/173964655 add proteomics differential
ebi-gene-expression-group/atlas-web-bulk pull request #87
Opened 2021-09-27 10:13 UTC by lingyun1010

This PR goes with web-core PR https://github.com/ebi-gene-expression-group/atlas-web-core/pull/69.

2021-10-15 13:01 UTC, alfonsomunozpomer requested changes
As with the companion PR, please be more observant of the relationship between the experiment type and the class/variable names that deal with them.

2021-10-15 13:01 UTC, alfonsomunozpomer commented on app/src/main/java/uk/ac/ebi/atlas/trader/GxaExperimentRepository.java
> +                return rnaSeqDifferentialExperimentFactory.create(
Inject and use `proteomicsDifferentialExperimentFactory`.

2021-10-15 13:01 UTC, alfonsomunozpomer commented on app/src/test/java/uk/ac/ebi/atlas/trader/GxaExperimentRepositoryIT.java
> +import static uk.ac.ebi.atlas.model.experiment.ExperimentType.*;
Don’t use wildcard imports (fix your settings in IDEA if this was your IDE “helping” you out).

2021-10-15 13:01 UTC, alfonsomunozpomer commented on app/src/main/java/uk/ac/ebi/atlas/experimentpage/json/JsonDifferentialExperimentController.java
> +            @ModelAttribute("preferences") @Valid MicroarrayRequestPreferences preferences,
Why `MicroArrayRequestPreferences`? Please use a suitable class, create it if necessary.

2021-10-15 13:01 UTC, alfonsomunozpomer commented on app/src/main/java/uk/ac/ebi/atlas/experimentpage/json/JsonDifferentialExperimentController.java
> +        return GSON.toJson(diffRnaSeqExperimentPageService.getResultsForExperiment(
If it’s a proteomics experiment the name should reflect it.

2021-10-20 12:33 UTC, upendrakumbham commented
I just tested the application with your latest core commit. Now experiments page is fine, I could see a list of experiments along with `E-PROT-39` experiment as well with Proteomics differential technology type.

I could see the result page as well after clicking `E-PROT-39` experiment

![image](https://user-images.githubusercontent.com/15771356/138093273-028cebf3-d021-48b7-abdd-96576ae32fdc.png)

2021-10-20 12:34 UTC, upendrakumbham commented
The above 3 buttons are not working for me. Please check from your side.

2021-10-27 11:43 UTC, upendrakumbham approved these changes
LGTM! I tested PR on my local machine. All issues got fixed.

2021-11-18 11:31 UTC, alfonsomunozpomer requested changes
Just some renaming business left to do. My only concern logic-wise would be to check if `ExperimentDownloadSupplier.Proteomics`  is a baseline-only related class. If that’s the case we should rename it so we don’t get confused about whether to use `ExperimentDownloadSupplier.BulkDifferential` when we have a differential proteomics experiment. If this is unclear please let me know.

2021-11-18 11:31 UTC, alfonsomunozpomer commented on app/src/main/java/uk/ac/ebi/atlas/experimentpage/ExperimentDownloadController.java
> +                                                    bulkDifferential,
This variable should be named `bulkDifferentialExperimentDownloadSupplier` to be consistent with the others.

2021-11-18 11:31 UTC, alfonsomunozpomer commented on app/src/main/java/uk/ac/ebi/atlas/experimentpage/ExpressionAtlasContentService.java
> +            ExperimentDownloadSupplier.BulkDifferential bulkDifferential,
Same as before, please rename to `bulkDifferentialExperimentDownloadSupplier`.

2021-11-18 11:31 UTC, alfonsomunozpomer commented on app/src/main/java/uk/ac/ebi/atlas/experimentpage/json/opentargets/OpenTargetsEvidenceController.java
> +    EvidenceService<DifferentialExpression, DifferentialExperiment, BulkDifferentialRequestContext, BulkDifferentialProfile>
Rename `diffRnaSeqEvidenceService`  to reflect the change in type. There are also other variables throughout this class with the same issue, please go through it carefully and change all references to `diffRnaSeq` elements.

2021-11-18 11:31 UTC, alfonsomunozpomer commented on app/src/test/java/uk/ac/ebi/atlas/experimentpage/FileDownloadControllerTest.java
> +    private ExperimentDownloadSupplier.BulkDifferential bulkDifferential;
Again, this should be `bulkDifferentialExperimentDownloadSupplier`.

2021-11-19 12:00 UTC, alfonsomunozpomer approved these changes
All fine. Remember to add the ticket we discussed to rename the proteomics baseline classes that are only denoted with `Proteomics`. Good job!

2021-11-22 09:50 UTC, merged